### PR TITLE
Support Gradle configuration cache.

### PR DESCRIPTION
**Pull request by edward3h**
Fix issues related to Gradle configuration cache. #204 

Add gradle-test-wrapper to support running Gradle tests against multiple Gradle versions.

### CODE REVIEW

**Comment by casid** [comment]
Thanks @edward3h!

This looks good and I would like to merge it, but the build got a lot slower.

_Build with maven_: 3-5 min (unchanged and unrelated. I'd still like to have this within 1 minute, but most of the time is eaten by the slow Kotlin compiler)
_Run all the Gradle Plugin tests_: 16-25 min (this seems quite slow, essentially the tests don't do much at all, I'd expect each to be done within a few seconds)

I feel we should try to speed up the Gradle tests before merging. Do you have an idea what could cause the slowdown?

**Comment by edward3h** [comment]
I made it run each test multiple times with different Gradle versions. I'll add a property to control that. I'm also not sure if running with TestKit added overhead. I'll take a look at timing.

**Comment by edward3h** [comment]
As a guess it was downloading and installing each gradle version in the CI build. I'm making it default to just running with the current version.

**Comment by casid** [comment]
Oh wow, that's much faster now! Thanks for looking into it, and also for contributing the Gradle configuration cache support.

**Pull request merged**
