### PR TITLE
Gradle path fix

### PR DESCRIPTION
**Pull request by edward3h**
I came across a build issue when trying to run the gradle tests in a dev environment. It doesn't seem to happen in the clean environment of the github workflow.

The fix is a minor change to build.gradle files.
I've added the shell script I was using to run all the tests locally.

Side note: https://github.com/nektos/act is an alternative way to run tests locally, with its own limitations.

### CODE REVIEW

**Comment by casid** [comment]
Thanks @edward3h!

I must admit, that my Gradle knowledge isn't very deep.

What's the difference between `java.srcDir` and `java.srcDirs`? I like that the Kotlin DSL and Groovy build files are very similar after your changes. Would still be interested to know what's going on :-)

I think we should also update the samples in the documentation: https://github.com/edward3h/jte/blob/gradle-path-fix/DOCUMENTATION.md#using-the-application-class-loader-since-120

**Comment by edward3h** [comment]
I am the opposite - I've worked on Gradle plugins but know little about Maven...

This is the javadoc for the type 'sourceSets.main.java' is referring to in build.gradle
https://docs.gradle.org/current/javadoc/org/gradle/api/file/SourceDirectorySet.html

The problem was use of "+=" operator, combined with confusing API definition here (what's the difference between getSrcDirs() and getSourceDirectories() ? It turns out quite a lot)

If you interpret the Groovy property references and operator overloading the line
`java.srcDirs += x`
becomes something like
```
Set<File> files = new HashSet<>(java.getSrcDirs())
files.add(x)
java.setSrcDirs(files)
```
Since the getSrcDirs() method doc says it doesn't filter and it forces a calculation of the contents, this is a problem. I guess that it is an older API that has been left for backwards compatibility. The newer Gradle style is to use wrapper types that defer calculation of the result until it is needed for actually running the task.

So anyway calling the 'srcDir(x)' method just tells the object to add the path, which is what we want. 'srcDirs(x)' would do exactly the same, it's just a version that can take multiple objects. I preferred the singular since there's only one in this case.

Also, I'll update the documentation page :)

**Comment by edward3h** [comment]
I'm hoping to enhance the Gradle plugin so that the project including the plugin doesn't have to do the sourceSet manipulation, by the way. But not in this PR.

**Comment by casid** [comment]
Oh wow! Thanks for the in-depth explanation! That actually makes a lot of sense and helped me grasp gradle a little bit better.

I'm merging this PR now.

Also - making the plugin usage simpler by getting rid of the sourceSet manipulation sounds great!

**Pull request merged**
