### PR TITLE
Updating kotlin version

### PR DESCRIPTION
**Pull request by Keksnet**
This adds compatibility with the latest kotlin version.

### CODE REVIEW

**Comment by casid** [comment]
Oh, thanks for the reminder. We tried to upgrade September last year and had to roll back because of class conflicts with the Kotlin version used in gradle: https://github.com/casid/jte/issues/177

I'll reopen the issue, so that we can move the discussion over there.

**Comment by casid** [comment]
I'm currently giving this a try in https://github.com/casid/jte/pull/202. Closing this PR.

**Comment by casid** [comment]
@Keksnet I just released jte 2.3.0 with this change in case you want to give it a try.

**Comment by Keksnet** [comment]
Thanks. I'll try it in a few hours together with ktor :D

**Pull request closed without merging**
