### PR TITLE
initial spring boot starter implementation

### PR DESCRIPTION
**Pull request by atomfrede**
Still lacks javadocs (if needed) and some how to documentation. Need to test it with the example repo

### CODE REVIEW

**Comment by atomfrede** [comment]
Tested it with the demo project, works fine now.

**Comment by casid** [comment]
Thank you for the contribution and sorry about the delay!

Will merge as soon as CI is through.

**Comment by atomfrede** [comment]
No need to hurry or apologize. And I see why intellij warned me about the Paths.of method. Will have a look later today.

**Comment by casid** [comment]
Thanks!

**Comment by casid** [comment]
I'm planning to release version 2.0.2 this weekend. Then, the spring boot starter will be available on central!

Thank you for all the work you put into this!

**Pull request merged**
