### PR TITLE
fix for a problem I encountered using binary static content

### PR DESCRIPTION
**Pull request by edward3h**
with generate in gradle build - missing resources directory.

Let's see if the workflow tests complete ok ;)

### CODE REVIEW

**Comment by edward3h** [comment]
So the workflow tests didn't :( It worked 'on my computer'. 
Will come back to this later in the week.

**Comment by edward3h** [comment]
Doh! The issue the workflow is failing on now is literally something I didn't implement in the native build support. It needs some additional configuration to tell it to load the `.bin` files.

**Comment by edward3h** [comment]
@casid a question about the binary support - why are the binary parts written to a separate file rather than e.g. byte arrays in the generated classes?

**Comment by casid** [comment]
> @casid a question about the binary support - why are the binary parts written to a separate file rather than e.g. byte arrays in the generated classes?

Byte array definitions are quite verbose. This is done to keep the class files small.

**Comment by casid** [comment]
Thank's for the fix!

**Pull request merged**
